accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, re_path

from accounts.views import signup, login, logout, profile_edit, password_change, user_follow, user_unfollow

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('edit/', profile_edit, name='profile_edit'),
    path('password_change/', password_change, name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', user_unfollow, name='user_unfollow'),

    # path()

]

instagram/urls.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.urls import path, re_path

from instagram.views import post_new, post_detail, user_page, index, post_like, post_unlike

app_name = 'instagram'

# UnicodeUsernameValidator.regex

urlpatterns = [
    path('', index, name='index'),
    path('post/new/', post_new, name='post_new'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/<int:pk>/like/', post_like, name='post_like'),
    path('post/<int:pk>/unlike/', post_unlike, name='post_unlike'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', user_page, name='user_page'),

]

instagram/models.py
import re

from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models import Model
from django.urls import reverse



class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

# user
# -> Post.objects.filter(author=user)
# -> user.post_set.all() -> 외래키 관계에서 자동으로 생성됨

class Post(BaseModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='my_post_set',
                               on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d")
    caption = models.CharField(max_length=500)
    tag_set = models.ManyToManyField('Tag', blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post_set', blank=True)

    def __str__(self):
        return self.caption


    def extract_tag_list(self):
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])

    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering = ['-id']

class Tag(models.Model):

    name = models.CharField(max_length=50, unique=True)
    def __str__(self):
        return self.name


# class LikeUser(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

instagram/forms.py
from django.forms import ModelForm, Textarea

from instagram.models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["photo", "caption", "location"]

        widgets = {
            "caption": Textarea,
        }

instagram/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from instagram.forms import PostForm
from instagram.models import Post

@login_required
def index(request):

    timesince = timezone.now() - timedelta(days=1)
    post_list = Post.objects.all().filter(
        Q(author=request.user) |
        Q(author__in=request.user.following_set.all())
    ).filter(
        created_at__gte=timesince
    )

    suggested_user_list = get_user_model().objects.all().exclude(pk=request.user.pk).exclude(pk__in=request.user.following_set.all())[:3]

    request.user.following_set.all()

    return render(request, "instagram/index.html", {
        "post_list": post_list,
        "suggested_user_list": suggested_user_list,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장했습니다.")
            # return redirect(reverse("root"))
            return redirect(post)
    else:
        form = PostForm()

    return render(request, "instagram/post_form.html", {
        "form": form,
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # comment_form = CommentForm()
    return render(request, "instagram/post_detail.html", {
        "post": post,
        # "comment_form": comment_form,
    })


def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)

    # 접속한 유저와 확인하는 유저가 팔로우가 되있는지 체크
    if request.user.is_authenticated:
        is_follow = request.user.following_set.filter(pk=page_user.pk).exists()
    else:
        is_follow = False

    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count() # 실제 데이터베이스에 count 쿼리를 던짐
    # len(post_list) # post리스트를 다 가져와서 메모리에 얹진다음에 리스트의 개수를 반환
    return render(request, 'instagram/user_page.html', {
        "page_user": page_user,
        "post_list": post_list,
        "post_list_count": post_list_count,
        "is_follow": is_follow,
    })

@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)

    messages.success(request, f"포스팅 #{post.pk}을 좋아합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)

    messages.success(request, f"포스팅 #{post.pk}번 좋아요를 취소합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "root")
    return redirect(redirect_url)

instagram/templates/instagram/_post_card.html
{% load instagram_tags %}

<div class="card">
    <div class="card-header">
        <img class="rounded-circle" src="{{ post.author.avatar_url }}" alt="" style="width :32px; height: 32px;">
        <a href="{% url "instagram:user_page" post.author.username %}">
            {{ post.author.name }}
        </a>

    </div>
    <div class="card-body">
        <img src="{{ post.photo.url }}" alt="" style="width: 100%;"/>

        {% for tag in post.tag_set.all %}
            <span class="badge bg-primary">
                #{{ tag.name }}
            </span>
        {% endfor %}
    </div>
    <div class="card-footer">
        {% if post|is_like_user:user %}
            <a href="{% url "instagram:post_unlike" post.pk %}" style="color: inherit;">
                <i class="fas fa-heart"></i>
            </a>
        {% else %}
            <a href="{% url "instagram:post_like" post.pk %}" style="color: inherit;">
                <i class="far fa-heart"></i>
            </a>
        {% endif %}

{#        {{ post|is_like_user:user }}#}




    </div>
</div>

instagram/templates/instagram/index.html
{% extends 'instagram/layout.html' %}

{% block content %}
    <div class="container mt-2">
        <div class="row mb-3">
            <div class="col-sm-12">
                Hanstagram
                <hr/>
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">새 프스팅 쓰기</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                {% for post in post_list %}
                    <div class="mb-3">
                        {% include "instagram/_post_card.html" %}
                    </div>
                {% empty %}
                    포스팅이 없습니다.
                {% endfor %}

            </div>
            <div class="col-sm-4">
                {% include 'instagram/timeline_sidebar.html' %}

            </div>
        </div>

    </div>

{% endblock content %}

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% include "instagram/_post_card.html" %}
            </div>
        </div>
    </div>

{% endblock %}

instagram/templates/instagram/post_form.html
{% extends "instagram/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6 offset-sm-3">
                {% include "_form.html" with form_title="새 포스팅 쓰기" submit_label="새 포스팅 쓰기" %}
            </div>
        </div>
    </div>
{% endblock %}

instagram/templates/instagram/timeline_sidebar.html
<div class="d-flex p-2 mb-3">
    <div class="me-md-2">
        <img src="{{ user.avatar_url }}" alt="" style="width: 48px; height: 48px;" class="rounded-circle">
    </div>

    <div>
        {{ user.username }}<br/>
        <small class="text-muted">
            {{ user.name }}
        </small>

    </div>
</div>

<div class="card mb-3">
    <div class="card-header">
        Stories
    </div>
    <div class="card-body">
        Stories from people you follow will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-header text-muted">
        Suggestions for you
    </div>
    <div class="card-body text-muted">
        {% for suggested_user in suggested_user_list %}
            {% include 'instagram/timeline_sidebar_user_follow.html' %}
        {% empty %}
            추천 친구가 없습니다.
        {% endfor %}

{#        {% include 'instagram/timeline_sidebar_user_follow.html' with friend_user=user %}#}
{#        {% include 'instagram/timeline_sidebar_user_follow.html' with friend_user=user %}#}
    </div>
</div>

instagram/templates/instagram/timeline_sidebar_user_follow.html
<div class="d-flex mb-1">
    <div class="me-md-2">
        <img src="{{ suggested_user.avatar_url }}" alt="" style="width: 32px; height: 32px;" class="rounded-circle">
    </div>
    <div class="">
        <a href="{% url "instagram:user_page" suggested_user.username %}">
            {{ suggested_user.username }}
        </a>

    </div>
    <div class="ms-auto">
        <a href="{% url "accounts:user_follow" suggested_user.username %}">Follow</a>
{#        <a href="{% url "user_unfollow" suggested_user.username %}">UnFollow</a>#}
    </div>
</div>

instagram/templates/instagram/user_page.html
{% extends 'instagram/layout.html' %}
{% load thumbnail %}

{% block content %}
    <div class="container">
        <div class="row pt-3 pb-3">
            <div class="col-sm-3" style="text-align: center;">
                <img src="{{ user.avatar_url }}" alt="" class="rounded-circle" style="width:200px; height: 250px;">
            </div>
            <div class="col-sm-9">
                {{ page_user.username }}
                <a href="{% url "accounts:profile_edit" %}" class="btn btn-secondary btn-sm">
                    Edit Profile
                </a>

{#                자기 자신을 제외하고 다른사람 user_page갔을 때 팔로우 인지 언팔인지 확인!#}
                {% if not request.user.username == page_user.username %}
                    {%  if is_follow %}
                        <a href="{% url "accounts:user_unfollow" page_user.username %}">UnFollow</a>
                    {% else %}
                        <a href="{% url "accounts:user_follow" page_user.username %}">Follow</a>
                    {% endif %}
                {% endif %}
{#                {{ is_follow }}#}

                <hr>
                - {{ post_list_count }} posts, 0 followers, 0 following
                <hr>
                {{ page_user.name }}
            </div>
        </div>

        <div class="row mt-3">
            {% for post in post_list %}
                <div class="col-sm-4 mb-3">
{#                    <img src="{{ post.photo.url }}" alt="{{ post.caption }}" style="width: 100%;">#}
                    <img src="{% thumbnail post.photo 256x256 crop %}" alt="{{ post.caption }}" style="width: 100%; object-fit: cover">
                </div>
            {% endfor %}
{#                {{ post_list }}#}
        </div>
    </div>
{% endblock %}