accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, re_path

from accounts.views import signup, login, logout, profile_edit, password_change, user_follow, user_unfollow

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('edit/', profile_edit, name='profile_edit'),
    path('password_change/', password_change, name='password_change'),
    re_path(r'^(?P<username>[\w.@+-]+)/follow/$', user_follow, name='user_follow'),
    re_path(r'^(?P<username>[\w.@+-]+)/unfollow/$', user_unfollow, name='user_unfollow'),

    # path()

]

instagram/urls.py
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.urls import path, re_path

from instagram.views import post_new, post_detail, user_page, index, post_like, post_unlike

app_name = 'instagram'

# UnicodeUsernameValidator.regex

urlpatterns = [
    path('', index, name='index'),
    path('post/new/', post_new, name='post_new'),
    path('post/<int:pk>/', post_detail, name='post_detail'),
    path('post/<int:pk>/like/', post_like, name='post_like'),
    path('post/<int:pk>/unlike/', post_unlike, name='post_unlike'),
    re_path(r'^(?P<username>[\w.@+-]+)/$', user_page, name='user_page'),

]

templates/_form.html
{% load bootstrap4 %}



<div class="card col-10">

    {% if form_title %}
        <div class="card-header">
            {{ form_title }}
        </div>
    {% endif %}

    <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
        {#                    <table>#}
        {#                        {{ form }}#}
        {#                    </table>#}
            {% buttons %}
                <button type="submit" class="btn btn-primary">
                    {{ submit_label|default:"Submit" }}
                </button>
            {% endbuttons %}
        </form>
    </div>

</div>

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Hanstagram</title>
    <link rel="stylesheet" href="{% static "bootstrap-5.1.3-dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="//pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="{% static "jquery-3.6.0.min.js" %}"></script>
    <script src="{% static "bootstrap-5.1.3-dist/js/bootstrap.min.js" %}"></script>

</head>
<body>


    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="border-bottom shadow-sm mb-3">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">

                    <div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-4 mb-2 bg-white">
                        <a href="{% url 'root' %}">
                            <h2 class="my-0 me-md-auto font-weight-normal">
                                <img src="{% static 'logo.png' %}" alt="Hanstagram" style="width: 150px">
                            </h2>
                        </a>


                        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                            <a class="py-2 text-dark text-decoration-none" href="#">
                                <svg aria-label="홈" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M45.5 48H30.1c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2.1-4.6-4.6-4.6s-4.6 2.1-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.6-.6 2.1 0l21.5 21.5c.3.3.4.7.4 1.1v23.5c.1.8-.6 1.5-1.4 1.5z"></path></svg>
                            </a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">
                                <path d="M45.5 48H30.1c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2.1-4.6-4.6-4.6s-4.6 2.1-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.6-.6 2.1 0l21.5 21.5c.3.3.4.7.4 1.1v23.5c.1.8-.6 1.5-1.4 1.5z"></path>
                            </a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">
                                <svg aria-label="Direct" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path></svg>
                            </a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">
                                <svg aria-label="새로운 게시물" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M31.8 48H16.2c-6.6 0-9.6-1.6-12.1-4C1.6 41.4 0 38.4 0 31.8V16.2C0 9.6 1.6 6.6 4 4.1 6.6 1.6 9.6 0 16.2 0h15.6c6.6 0 9.6 1.6 12.1 4C46.4 6.6 48 9.6 48 16.2v15.6c0 6.6-1.6 9.6-4 12.1-2.6 2.5-5.6 4.1-12.2 4.1zM16.2 3C10 3 7.8 4.6 6.1 6.2 4.6 7.8 3 10 3 16.2v15.6c0 6.2 1.6 8.4 3.2 10.1 1.6 1.6 3.8 3.1 10 3.1h15.6c6.2 0 8.4-1.6 10.1-3.2 1.6-1.6 3.1-3.8 3.1-10V16.2c0-6.2-1.6-8.4-3.2-10.1C40.2 4.6 38 3 31.8 3H16.2z"></path><path d="M36.3 25.5H11.7c-.8 0-1.5-.7-1.5-1.5s.7-1.5 1.5-1.5h24.6c.8 0 1.5.7 1.5 1.5s-.7 1.5-1.5 1.5z"></path><path d="M24 37.8c-.8 0-1.5-.7-1.5-1.5V11.7c0-.8.7-1.5 1.5-1.5s1.5.7 1.5 1.5v24.6c0 .8-.7 1.5-1.5 1.5z"></path><svg aria-label="Direct" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2 6.1h35.5L18 18.7 5.2 6.1zm18.7 33.6l-4.4-18.4L42.4 8.6 23.9 39.7z"></path></svg></svg>
                            </a>
                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">
                                <svg aria-label="사람 찾기" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path clip-rule="evenodd" d="M24 0C10.8 0 0 10.8 0 24s10.8 24 24 24 24-10.8 24-24S37.2 0 24 0zm0 45C12.4 45 3 35.6 3 24S12.4 3 24 3s21 9.4 21 21-9.4 21-21 21zm10.2-33.2l-14.8 7c-.3.1-.6.4-.7.7l-7 14.8c-.3.6-.2 1.3.3 1.7.3.3.7.4 1.1.4.2 0 .4 0 .6-.1l14.8-7c.3-.1.6-.4.7-.7l7-14.8c.3-.6.2-1.3-.3-1.7-.4-.5-1.1-.6-1.7-.3zm-7.4 15l-5.5-5.5 10.5-5-5 10.5z" fill-rule="evenodd"></path></svg>
                            </a>

                            <a class="me-3 py-2 text-dark text-decoration-none" href="#">
                                <svg aria-label="활동 피드" class="_8-yf5 " color="#262626" fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                            </a>

{#                            <img src="{% url 'pydenticon_image' ha %}" alt="img" style="width: 24px; height: 24px; object-fit: cover; border-radius: 50%;">#}
{#                            {% url 'pydenticon_image' user.is_authenticated %}#}
{#                            <img src="{% url 'pydenticon_image' user.is_authenticated %}" alt="img" style="width: 24px; height: 24px; object-fit: cover; border-radius: 50%;">#}
                            {% if user.is_authenticated %}
                                <a class="me-3 py-2 text-dark text-decoration-none" href="{% url "accounts:profile_edit" %}">
                                    <img src="{{ user.avatar_url }}" class="rounded-circle" alt="img" style="width: 24px; height: 24px; object-fit: cover; border-radius: 50%;">
{#                                {% if user.avatar %}#}
{#                                    <img src="{{ user.avatar.url }}" alt="img" style="width: 24px; height: 24px;">#}
{#                                {% else %}#}
{#                                    <img src="{% url 'pydenticon_image' user.is_authenticated %}" alt="img" style="width: 24px; height: 24px; object-fit: cover; border-radius: 50%;">#}
{#                                {% endif %}#}

{#                                <img alt="kimhan1113님의 프로필 사진" style="border-radius: 50%; object-fit: cover; width: 22px; height: 22px;" class="_6q-tv" crossorigin="anonymous" data-testid="user-avatar" draggable="false" src="{% static "hans.jpg" %}">#}
                                </a>
                            {% endif %}
                            {% if user.is_authenticated %}

                                <div class="me-3 py-2 text-dark text-decoration-none" style="background-color: #ccd0d4; border-radius: 20px; width:70px; height:30px; text-align: center; position:relative; top: 7px;">
                                    <a href="{% url "accounts:logout" %}" style="color: white; font-size: 11px; text-decoration: none; position:relative; bottom: 5px;">
                                        로그아웃
                                    </a>

                                </div>

                            {% endif %}

{#                            <div>#}
{#                                {{ user.name }}#}
{#                            </div>#}

                        </nav>

                    </div>

                </div>
            </div>
        </div>
    </div>
{#        <div class="d-flex flex-column flex-md-row align-items-center pb-3 px-md-4 mb-4 bg-white border-bottom">#}


{% block content %}

{% endblock content %}


{#        </div>#}



</body>
</html>

templates/root.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container mt-2">
        <div class="row">
            <div class="col-sm-12">
                Hanstagram
                <hr/>
                <a href="{% url 'instagram:post_new' %}" class="btn btn-primary">새 프스팅 쓰기</a>
            </div>
        </div>

    </div>

{% endblock content %}